name: meli_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pandas
  - requests
  - tqdm
  - scikit-learn
  - matplotlib
  - seaborn
  - nltk
  - jupyter
  - ipykernel
  - transformers
  - pip
  - pip:
      - sentence-transformers  # Biblioteca para embeddings
      - umap-learn

